task/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("taskapp.urls")),
    # path('question/', include("taskapp.urls")),
    path('', include('taskapi.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskapp/urls.py
from django.urls import path
from . import views
from taskapp.views import SignUpView, LoginView, LogoutView, QuestionView, AnswerView, IndexView, QuestionDetailView, QuestionCategoryView

app_name = 'taskapp'
urlpatterns= [
    path('', IndexView.as_view(), name='index'),

    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    # path('register', views.register, name="register"),
    path('add-question/', QuestionView.as_view(), name="question_create"),
    path('add-answer/', AnswerView.as_view(), name="answer_create"),
    path("register/", SignUpView.as_view(), name='signup'),
    path('detail/<int:pk>/', QuestionDetailView.as_view(), name="detail_question"),
    path('question_categories/<int:pk>', QuestionCategoryView.as_view(), name='question_category'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/question.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,400i,500,600,700&display=swap"
          rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
</head>
<body>

{% include 'header.html' %}

{% block content %}
{% endblock %}

{% include 'footer.html' %}
<script src=" https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/filter.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/footer.html
{% load static %}
{% block content %}
<div class="container-fluid footer">
    <div class="container">
        <div class="col-md-12 footer-div">
            <div class="col-md-4 footer1">
                <img src="{% static 'img/logo-footer.png' %}"/>
                <p>Discy is a social questions & Answers Engine which will help you establis your community and connect
                    with other people.</p>
            </div>
            <div class="col-md-4 footer2">
                <h4>About us</h4>
                <ul>
                    <li>
                        <a href="#">
                            <h5>Meet the team</h5>
                        </a>
                        <a href="#">
                            <h5>Contact us </h5>
                        </a>
                        <a href="#">
                            <h5>About us</h5>
                        </a>
                        <a href="#">
                            <h5>Site Name : {{ config.SITE_NAME }}</h5>
                        </a>
                    </li>
                </ul>
            </div>
            <!---Links--->
            <div class="col-md-4 footer3">
                <h4>Follow</h4>
                <ul>
                    <li>
                        <a href="#">
                            <img src="{% static 'img/ficon.png' %}"/>
                        </a>
                        <a href="#">
                            <img src="{% static 'img/insta.png' %}"/>
                        </a>
                        <a href="#">
                            <img src=" {% static 'img/twitter.png' %}"/>
                        </a>
                        <a href="#">
                            <img src=" {% static 'img/linkedin.png' %}"/>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/header.html
{% load static %}
{% block content %}
    <div class="container-fluid mainheader-sec" style="display:None;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-2 logo">
                    <a href="#">
                        <img class="img-responsive" src="{% static 'img/logo.png' %}"/>
                    </a>
                </div>
                <div class="col-md-8 texttag">
                    <a href="#"><h5>Home</h5></a>
                    <a href="#"><h5>About us </h5></a>
                    <a href="#"><h5>Contact us</h5></a>
                    <div class="search-container">
                        <form action="/action_page.php">
                            <input name="search" placeholder="Type of Search.." type="text">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div>

                <div class="col-md-1 padding0">
                    <button class="btn btn-info btn-lg btn-insign" data-target="#signin" data-toggle="modal"
                            type="button">Sign in
                    </button>
                </div>
                <div class="col-md-1">
                    <button class="btn btn-info btn-lg btn-upsign" data-target="#signup" data-toggle="modal"
                            type="button">Sign up
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-inverse header">
    <div class="container-fluid  padding0">
        <div class="col-md-12 padding-xs-0">
            <div class="col-md-3 col-sm-2 col-xs-12">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#">
                        <img class="img-responsive logo-image" src="{% static 'img/logo.png' %}"/>
                    </a>
                </div>
            </div>
            <div class="col-md-8 col-sm-10 col-xs-12">
                <div class="collapse navbar-collapse" id="myNavbar">
                    <div class="col-sm-9 col-xs-12">
                        <ul class="nav navbar-nav">
                            <li class="active homepadd"><a href="{% url 'taskapp:index' %}">Home</a></li>
                            <li class="homepadd"><a href="#">About Us</a></li>
                            <li class="homepadd1">
                                <form action="#" class="side-div">
                                    <input class="form-control" name="search" placeholder="Type of Search.."
                                           type="text">
                                    <button class="btn" type="submit"><i class="fa fa-search"></i></button>
                                </form>
                            </li>
                        </ul>
                    </div>
                    {% if user.is_authenticated %}
                        <h3 style="color: white">Hello : {{ user.firstname }}</h3>
                        <div class="col-md-2 col-sm-2 col-xs-6"><a href="{% url 'taskapp:logout' %}">
                            <button class="btn btn-info btn-lg btn-insign"
                                    type="button">Sign out
                            </button>
                        </a>
                        </div>
                        {#                    {% endif %}#}
                    {% else %}
                        <div class="col-md-2 col-sm-2 col-xs-6">
                            <button class="btn btn-info btn-lg btn-insign" data-target="#signin" data-toggle="modal"
                                    type="button">Sign in
                            </button>
                        </div>
                        <div class="col-md-1 col-sm-1 col-xs-6 padding0">
                            <button class="btn btn-info btn-lg btn-upsign" data-target="#signup" data-toggle="modal"
                                    type="button">Sign up
                            </button>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>
<!-- Sign In Modal -->
<div class="modal fade model-insign" id="signin" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button class="close active" data-dismiss="modal" type="button">&times;</button>
                <h4>Sign in</h4>
                <p>Login to our social questions & Answers Engine to ask questions answer
                    people’s questions & connect with other people.</p>
            </div>

            <div class="modal-body">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="col-md-5 col-xs-5 col-sm-5 modeldiv">

                        <a href="{% url 'taskapp:signup' %}">
                            <button>sign up here</button>
                        </a>
                    </div>
                    <div class="col-md-7 col-xs-7 col-sm-7 username">
                        <form action="{% url "taskapp:login" %} " method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="usr">Email:</label>
                                <input class="form-control user-xs" id="usr" type="email" name="email">
                            </div>
                            <div class="form-group">
                                <label for="pwd">Password:</label>
                                <input class="form-control" id="pwd" type="password" name="password">
                            </div>

                            <div class="col-md-12 padding0">
                                <div class="col-md-6 padding0">
                                    <div class="checkbox">
                                        <label><input type="checkbox" value="">Remember Me!</label>
                                    </div>
                                </div>
                                <div class="col-md-6 forget-password padding0">
                                    <a href="#">
                                        <h6>Forget Your Password? </h6>
                                    </a>
                                </div>
                            </div>
                            <button class="inlog">Log In</button>
                        </form>
                        <div>
                            {% for message in messages %}
                            <h3> {{ message }}</h3>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sign Up Modal -->
<div class="modal fade model-upsign" id="signup" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content content-padd">
            <div class="modal-header">
                <button class="close" data-dismiss="modal" type="button">&times;</button>
                <h4>Sign up</h4>
                <p>Login to our social questions & Answers Engine to ask questions answer people’s
                    questions & connect with other people.</p>
            </div>
            <div class="modal-body">
                <div class="col-md-12 col-xs-12 col-sm-12">
                    <div class="col-md-5 col-xs-5 col-sm-5 upsign-div">
                        <button class="btn">Have an account? Sign in</button>
                    </div>
                    <div class="col-md-7 col-xs-12 col-sm-12 upsign-userdiv">
                        <form action="{% url "taskapp:signup" %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {#                            {{ form.as_p }}#}
                            <div class="form-group">
                                <label for="user">firstname:</label>
                                <input class="form-control" id="fname" type="text" name="firstname" required>
                            </div>
                            <div class="form-group">
                                <label for="user">lastname:</label>
                                <input class="form-control" id="lname" type="text" name="lastname" required>
                            </div>
                            {#                            <div class="form-group">#}
                            {#                                <label for="user">Username:</label>#}
                            {#                                <input class="form-control" id="user" type="text" name="username">#}
                            {#                            </div>#}
                            <div class="form-group">
                                <label for="e-mail">E-mail:</label>
                                <input class="form-control" id="e-mail" type="email" name="email" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Password:</label>
                                <input class="form-control" id="password" type="password" name="password"  required>
                            </div>
                            <div class="form-group">
                                <label for="password">Confirm Password:</label>
                                <input class="form-control" id="confirm password" type="password" name="password2" required>
                            </div>
                            <div class="form-group">
                                <label for="password">User image:</label>
                                <input class="form-control"  type="file" name="image" required>
                            </div>

                            {#                            <div class="form-group">#}
                            {#                                <label for="password">Confirm Password:</label>#}
                            {#                                <input class="form-control" id="confirm_password" type="password" name="password2">#}
                            {#                            </div>#}

                            <div class="checkbox">
                                <label><input type="checkbox" value="">I agree with the T&C</label>
                            </div>
                            <button>Sign up</button>
                        </form>
                        <div>
                            {% for message in messages %}
                            <h3> {{ message }}</h3>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/index1.html
<doctype/>
<html>
<head>
    <title>Question sheet</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/question1.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,400i,500,600,700&display=swap"
          rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
</head>
<body>
<!--     <div class="modal ask-modal fade" id="ask_a_question" role="dialog">-->
<!--                            <div class="modal-dialog askque">-->
<!--&lt;!&ndash;&ndash;&gt;-->
<!--                                &lt;!&ndash; Modal content&ndash;&gt;-->
<!--                                <div class="modal-content">-->
<!--                                    <div class="modal-header ask-head">-->
<!--                                        <button class="close active askclotiv" data-dismiss="modal" type="button">-->
<!--                                            &times;-->
<!--                                        </button>-->
<!--                                        <h4 class="modal-title">-->
<!--                                        </h4>-->
<!--                                    </div>-->
<!--&lt;!&ndash;&ndash;&gt;-->
<!--                                    <div class="modal-body">-->
<!--                                         <div class="col-md-12 col-sm-12 col-xs-12">-->
<!--                <div class="col-md-5 col-sm-5 col-xs-5 main-image">-->
<!--                </div>-->
<!--                <div class="col-md-7 col-sm-7 col-xs-7">-->
<!--                    <div class="col-md-12 col-sm-12 col-xs-12 edit-question">-->
<!--                        <h2>Edit Questions</h2>-->
<!--                        <p>How Likely are you to recommend our product...</p>-->
<!--                    </div>-->
<!--                    <div class="col-md-12 col-sm-12 col-xs-12">-->
<!--                        <div class="form-group question-type">-->
<!--                            <label>Question Type:</label>-->
<!--                            <select>-->
<!--                                <option>New source recommend.... </option>-->
<!--                                <option>to get the best answer</option>-->
<!--                                <option>And whom can be the best</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-md-12 col-sm-12 col-xs-12">-->
<!--                        <div class="form-group how-likely">-->
<!--                            <label>Title:</label>-->
<!--                            <input type="text" placeholder="How Likely are you to recommend our product in red handed...."/>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-md-12 col-sm-12 col-xs-12">-->
<!--                        <div class="form-group how-likely">-->
<!--                            <label> SubTitle:</label>-->
<!--                            <input type="text"/>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-sm-12 col-md-12 col-xs-12 button-div">-->
<!--                        <button>Submit</button>-->
<!--                    </div>-->
<!--                </div>-->
<!--&lt;!&ndash;&ndash;&gt;-->
<!--&lt;!&ndash;            </div>&ndash;&gt;-->
<!--&lt;!&ndash;                                    </div>&ndash;&gt;-->
<!--&lt;!&ndash;                                </div>&ndash;&gt;-->

<!--&lt;!&ndash;                            </div>&ndash;&gt;-->
<!--&lt;!&ndash;                        </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    </div>&ndash;&gt;-->
<!--     &lt;!&ndash;<div class="container-fluid">&ndash;&gt;-->
<!--&lt;!&ndash;            <div class="container">&ndash;&gt;-->
<!--&lt;!&ndash;            <div class="col-md-12 col-sm-12 col-xs-12">&ndash;&gt;-->
<!--&lt;!&ndash;                <div class="col-md-5 col-sm-5 col-xs-5 main-image">&ndash;&gt;-->
<!--&lt;!&ndash;                </div>&ndash;&gt;-->
<!--&lt;!&ndash;                <div class="col-md-7 col-sm-7 col-xs-7">&ndash;&gt;-->
<!--&lt;!&ndash;                    <div class="col-md-12 col-sm-12 col-xs-12 edit-question">&ndash;&gt;-->
<!--&lt;!&ndash;                        <h2>Edit Questions</h2>&ndash;&gt;-->
<!--&lt;!&ndash;                        <p>How Likely are you to recommend our product...</p>&ndash;&gt;-->
<!--&lt;!&ndash;                    </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    <div class="col-md-12 col-sm-12 col-xs-12">&ndash;&gt;-->
<!--&lt;!&ndash;                        <div class="form-group question-type">&ndash;&gt;-->
<!--&lt;!&ndash;                            <label>Question Type:</label>&ndash;&gt;-->
<!--&lt;!&ndash;                            <select>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option>New source recommend.... </option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option>to get the best answer</option>&ndash;&gt;-->
<!--&lt;!&ndash;                                <option>And whom can be the best</option>&ndash;&gt;-->
<!--&lt;!&ndash;                            </select>&ndash;&gt;-->
<!--&lt;!&ndash;                        </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    <div class="col-md-12 col-sm-12 col-xs-12">&ndash;&gt;-->
<!--&lt;!&ndash;                        <div class="form-group how-likely">&ndash;&gt;-->
<!--&lt;!&ndash;                            <label>Title:</label>&ndash;&gt;-->
<!--&lt;!&ndash;                            <input type="text" placeholder="How Likely are you to recommend our product in red handed...."/>&ndash;&gt;-->
<!--&lt;!&ndash;                        </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    <div class="col-md-12 col-sm-12 col-xs-12">&ndash;&gt;-->
<!--&lt;!&ndash;                        <div class="form-group how-likely">&ndash;&gt;-->
<!--&lt;!&ndash;                            <label> SubTitle:</label>&ndash;&gt;-->
<!--&lt;!&ndash;                            <input type="text"/>&ndash;&gt;-->
<!--&lt;!&ndash;                        </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    <div class="col-sm-12 col-md-12 col-xs-12 button-div">&ndash;&gt;-->
<!--&lt;!&ndash;                        <button>Submit</button>&ndash;&gt;-->
<!--&lt;!&ndash;                    </div>&ndash;&gt;-->
<!--&lt;!&ndash;                </div>&ndash;&gt;-->
<!--&lt;!&ndash;&lt;!&ndash;&ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;            </div>&ndash;&gt;-->
<!--&lt;!&ndash;&lt;!&ndash;&ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;&ndash;&gt;-->
<!--            </div>-->
<!--&lt;!&ndash;&ndash;&gt;-->
<!--        </div>-->
<!---->
<!---->

                    <div class="col-md-12  col-xs-12 col-sm-12 ask-question">
                        <button class="btn btn-info btn-lg btn-insign1" data-target="#ask_a_question" data-toggle="modal"
                                type="button">Ask A Question
                        </button>

                        <!-- Modal -->
                        <div class="modal ask-modal fade" id="ask_a_question" role="dialog">
                            <div class="modal-dialog askque">

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header ask-head">
                                         <div class="col-md-10 col-sm-10 col-xs-10 edit-question">
                                                <h2>Edit Questions</h2>
                                                <p>How Likely are you to recommend our product...</p>
                                            </div>
                                        <h4 class="modal-title">
                                        </h4>
                                    </div>

                                    <div class="modal-body">
                                        <div class="col-md-12 col-sm-12 col-xs-12 body-main">
                                            <div class="col-md-5 col-sm-5 col-xs-5 main-image">
                                            </div>
                                            <div class="col-md-7 col-sm-7 col-xs-7">
                                            <div class="col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group question-type">
                                                    <label>Question Type:</label>
                                                    <select>
                                                        <option>New source recommend.... </option>
                                                        <option>to get the best answer</option>
                                                        <option>And whom can be the best</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group how-likely">
                                                    <label>Title:</label>
                                                    <input type="text" placeholder="How Likely are you to recommend our product in red handed...."/>
                                                </div>
                                            </div>
                                            <div class="col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group how-likely">
                                                    <label> SubTitle:</label>
                                                    <input type="text"/>
                                                </div>
                                            </div>
                                            <div class="col-sm-12 col-md-12 col-xs-12 button-div">
                                                <button>Submit</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>








                                        <!--                </div>-->
<!--                <div class="col-md-7 col-sm-7 col-xs-7">-->
<!--                    <div class="col-md-12 col-sm-12 col-xs-12 edit-question">-->
<!--                        <h2>Edit Questions</h2>-->
<!--                        <p>How Likely are you to recommend our product...</p>-->
<!--                    </div>-->
<!--                    <div class="col-md-12 col-sm-12 col-xs-12">-->
<!--                        <div class="form-group question-type">-->
<!--                            <label>Question Type:</label>-->
<!--                            <select>-->
<!--                                <option>New source recommend.... </option>-->
<!--                                <option>to get the best answer</option>-->
<!--                                <option>And whom can be the best</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-md-12 col-sm-12 col-xs-12">-->
<!--                        <div class="form-group how-likely">-->
<!--                            <label>Title:</label>-->
<!--                            <input type="text" placeholder="How Likely are you to recommend our product in red handed...."/>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-md-12 col-sm-12 col-xs-12">-->
<!--                        <div class="form-group how-likely">-->
<!--                            <label> SubTitle:</label>-->
<!--                            <input type="text"/>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-sm-12 col-md-12 col-xs-12 button-div">-->
<!--                        <button>Submit</button>-->
<!--                    </div>-->
<!--                </div>-->
<!--&lt;!&ndash;&ndash;&gt;-->
<!--            </div>-->
<!--&lt;!&ndash;&ndash;&gt;-->
<!---->
            </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>




















<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</body>
</html>